atados/atados/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template, redirect_to
from django.utils.translation import ugettext_lazy as _
from atados.atados.forms import AuthenticationForm, SearchForm
from atados.atados.views import home
from haystack.views import SearchView

urlpatterns = patterns(
    '',

    url(r'^$', home, name='home'),

    url(_(r'^sign-in$'), 'django.contrib.auth.views.login',
        {'authentication_form': AuthenticationForm,
         'template_name': 'atados/atados/sign-in.html'}, name='sign-in'),

    url(r'^sign-in$', redirect_to,
        {'url': _('/sign-in'),
         'query_string': True}, name='global-sign-in'),

    url(_(r'^sign-out$'), 'django.contrib.auth.views.logout',
        {'next_page': _('/sign-in')}, name='sign-out'),

    url(_(r'^search$'), SearchView(form_class=SearchForm), name='search'),

    url(_(r'^terms$'), direct_to_template,
        {'template': 'atados/atados/terms.html'}, name='terms'),

    url(_(r'^privacy$'), direct_to_template,
        {'template': 'atados/atados/privacy.html'}, name='privacy'),

    url(_(r'^security$'), direct_to_template,
        {'template': 'atados/atados/security.html'}, name='security'),

    url(_(r'^about$'), direct_to_template,
        {'template': 'atados/atados/about.html'}, name='about'),
)

atados/nonprofit/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template, redirect_to
from django.utils.translation import ugettext_lazy as _
from atados.atados.forms import AuthenticationForm
from atados.nonprofit.views import (NonprofitPictureUpdateView,
                                       NonprofitDetailsUpdateView)
from registration.views import register, activate

urlpatterns = patterns(
    '',

    url(_(r'^nonprofit/sign-up$'), register,
        {'backend': 'atados.nonprofit.backends.RegistrationBackend',
         'template_name': 'atados/nonprofit/sign-up.html'},
        name='sign-up'),

    url(_(r'^nonprofit/sign-up-confirmartion/(?P<activation_key>\w+)$'), activate,
        {'backend': 'atados.nonprofit.backends.RegistrationBackend',
         'template_name': 'atados/nonprofit/sign-up-activation.html'},
        name='sign-up-confirmation'),

    url(_(r'^nonprofit/sign-up-activation-complete$'), direct_to_template, {'template': 'atados/nonprofit/sign-up-activation-complete.html'},
        name='sign-up-activation-complete'),

    url(_(r'^nonprofit/sign-up-complete$'), direct_to_template, {'template': 'atados/nonprofit/sign-up-complete.html'},
        name='sign-up-complete'),

    url(_(r'^(?P<nonprofit>[-\w]+)/edit-nonprofit-picture$'), NonprofitPictureUpdateView.as_view(),
        name='edit-nonprofit-picture'),

    url(_(r'^(?P<nonprofit>[-\w]+)/edit-nonprofit-details$'), NonprofitDetailsUpdateView.as_view(),
        name='edit-nonprofit-details'),
)

atados/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template, redirect_to
from django.utils.translation import ugettext_lazy as _
from atados.nonprofit.views import NonprofitBaseView
from atados.project.views import (ProjectDonationCreateView,
                                  ProjectWorkCreateView,
                                  ProjectJobCreateView,
                                  ProjectDetailsView, ProjectUpdateView,
                                  ProjectCollaboratorsView,
                                  ProjectDeleteView,
                                  ProjectApplyView,
                                  ProjectPictureUpdateView)

urlpatterns = patterns(
    '',

    url(_(r'^project$'), direct_to_template, {'template': 'atados/project/index.html'}, name='index'),
    url(_(r'^(?P<nonprofit>[-\w]+)/add-new-project$'), NonprofitBaseView.as_view(template_name='atados/project/project-kind-choose.html'), name='new'),
    url(_(r'^(?P<nonprofit>[-\w]+)/add-new-project/donation$'), ProjectDonationCreateView.as_view(), name='new-donation'),
    url(_(r'^(?P<nonprofit>[-\w]+)/add-new-project/work$'), ProjectWorkCreateView.as_view(), name='new-work'),
    url(_(r'^(?P<nonprofit>[-\w]+)/add-new-project/job$'), ProjectJobCreateView.as_view(), name='new-job'),
    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)$'), ProjectDetailsView.as_view(), name='details'),
    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)/edit$'), ProjectUpdateView.as_view(), name='edit'),
    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)/collaborators$'), ProjectCollaboratorsView.as_view(), name='collaborators'),
    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)/delete$'), ProjectDeleteView.as_view(), name='delete'),
    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)/apply$'), ProjectApplyView.as_view(), name='apply'),

    url(_(r'^(?P<nonprofit>[-\w]+)/(?P<project>[-\w]+)/picture$'), ProjectPictureUpdateView.as_view(),
        name='edit-project-picture'),
)

atados/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext_lazy as _
from django.contrib import admin
from atados.views import slug

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url('', include('atados.atados.urls', namespace='atados')),
    url('', include('atados.nonprofit.urls', namespace='nonprofit')),
    url('', include('atados.volunteer.urls', namespace='volunteer')),
    url('', include('atados.project.urls', namespace='project')),
    url(_(r'^(?P<slug>[-\w]+)$'), slug, name='slug'),
)

atados/project/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from atados.nonprofit.models import Nonprofit
from atados.volunteer.models import Volunteer
from sorl.thumbnail import ImageField
from time import time
from datetime import datetime


WEEKDAYS = (
        (1, _('Monday')),
        (2, _('Tuesday')),
        (3, _('Wednesday')),
        (4, _('Thursday')),
        (5, _('Friday')),
        (6, _('Saturday')),
        (0, _('Sunday')),
)

PERIODS = (
        (0, _('Morning')),
        (1, _('Afternoon')),
        (2, _('Evening')),
)

class Availability(models.Model):
    weekday = models.PositiveSmallIntegerField(_('weekday'), choices=WEEKDAYS)
    period = models.PositiveSmallIntegerField(_('period'), choices=PERIODS)

    def __unicode__(self):
        return _('%s at %s') % (self.get_weekday_display(), self.get_period_display())

class Cause(models.Model):
    name = models.CharField(_('name'), max_length=30)

    def __unicode__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(_('name'), max_length=30)

    def __unicode__(self):
        return self.name

class ProjectManager(models.Manager):
    use_for_related_fields = True

    def active(self):
        return self.get_query_set().filter(deleted=False)

    def published(self):
        return self.get_query_set().active(published=True)

class Project(models.Model):
    objects = ProjectManager()
    nonprofit = models.ForeignKey(Nonprofit)
    causes = models.ManyToManyField(Cause)
    name = models.CharField(_('Project name'), max_length=50)
    slug = models.SlugField(max_length=50)
    details = models.TextField(_('Details'), max_length=1024)
    responsible = models.CharField(_('Responsible name'), max_length=50)
    phone = models.CharField(_('Phone'), max_length=20)
    email = models.EmailField(_('E-mail address'))
    zipcode = models.CharField(_('Zip code'), max_length=10,
                               blank=True, null=True, default=None)
    addressline = models.CharField(_('Address line'), max_length=200,
                                  blank=True, null=True, default=None)
    neighborhood = models.CharField(_('Neighborhood'), max_length=50,
                                    blank=True, null=True, default=None)
    city = models.CharField(_('City'), max_length=50,
                            blank=True, null=True, default=None)
    vacancies = models.PositiveSmallIntegerField(_('Vacancies'),
                                    blank=True, null=True, default=None)
    published = models.BooleanField(_("Published"), default=False)
    deleted = models.BooleanField(_("Deleted"), default=False)
    deleted_date = models.DateTimeField(_("Deleted date"), blank=True,
                                        null=True)

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.deleted_date = datetime.now()
        self.save()

    def image_name(self, filename):
        left_path, extension = filename.rsplit('.', 1)
        return 'project/%s/%s/%s.%s' % (self.nonprofit.slug,
                                        time(), self.slug, extension)

    image = ImageField(upload_to=image_name, blank=True,
                       null=True, default=None)

    def __unicode__(self):
        return  '%s - %s' % (self.name, self.nonprofit.name)

    @models.permalink
    def get_absolute_url(self):
        return ('project:details', (self.nonprofit.slug, self.slug))

    @models.permalink
    def get_edit_url(self):
        return ('project:edit', (self.nonprofit.slug, self.slug))

    @models.permalink
    def get_delete_url(self):
        return ('project:delete', (self.nonprofit.slug, self.slug))

    def get_project_type(self):
        return self.project_type

    class Meta:
        unique_together = (("slug", "nonprofit"),)

class ProjectDonation(Project):
    objects = ProjectManager()
    project_type = 'donation'
    collection_by_nonprofit = models.BooleanField(
            _('Collection made by the nonprofit'))

class ProjectWork(Project):
    objects = ProjectManager()
    project_type = 'work'
    availabilities = models.ManyToManyField(Availability)
    prerequisites = models.TextField(_('Prerequisites'), max_length=1024)
    skills = models.ManyToManyField(Skill)
    weekly_hours = models.PositiveSmallIntegerField(_('Weekly hours'),
                                        blank=True, null=True)
    can_be_done_remotely = models.BooleanField(
            _('This work can be done remotely.'))

class ProjectJob(ProjectWork):
    objects = ProjectManager()
    project_type = 'job'

class Apply(models.Model):
    volunteer = models.ForeignKey(Volunteer)
    project = models.ForeignKey(Project)

atados/volunteer/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from time import time


class Volunteer(models.Model):
    user = models.ForeignKey(User)

    def image_name(self, filename):
        left_path, extension = filename.rsplit('.', 1)
        return 'volunteer/%s/%s.%s' % (time(), self.user.username, extension)

    image = ImageField(upload_to=image_name, blank=True,
                       null=True, default=None)

    @models.permalink
    def get_absolute_url(self):
        return ('slug', (self.user.username,))

    def __unicode__(self):
        return self.user.first_name

atados/atados/views.py
from django import http
from django.utils import simplejson as json
from django.http import Http404
from django.views.generic.simple import direct_to_template
from django.contrib.auth.models import User
from atados.volunteer.views import VolunteerDetailsView, VolunteerHomeView
from atados.volunteer.forms import RegistrationForm
from atados.nonprofit.views import NonprofitDetailsView, NonprofitHomeView
from atados.nonprofit.models import Nonprofit


template_name = 'atados/atados/home.html'

def home(request, *args, **kwargs):
    if request.user.is_authenticated():
        try:
            Nonprofit.objects.get(user=request.user)
            return NonprofitHomeView.as_view()(request, *args, **kwargs)
        except Nonprofit.DoesNotExist:
            return VolunteerHomeView.as_view()(request, *args, **kwargs)

    return direct_to_template(request, 'atados/atados/home.html',
                              {'form': RegistrationForm()})

def slug(request, *args, **kwargs):
    try:
        User.objects.get(username=kwargs['slug'])
        kwargs.update({
            'username': kwargs.pop('slug')
        })
        return VolunteerDetailsView.as_view()(request, *args, **kwargs)
    except User.DoesNotExist:
        try:
            Nonprofit.objects.get(slug=kwargs['slug'])
            kwargs.update({
                'nonprofit': kwargs.pop('slug')
            })
            return NonprofitDetailsView.as_view()(request, *args, **kwargs)
        except Nonprofit.DoesNotExist:
            raise Http404

class JSONResponseMixin(object):

    def render_to_response(self, context):
        return self.get_json_response(self.convert_context_to_json(context))

    def get_json_response(self, content, **httpresponse_kwargs):
        return http.HttpResponse(content, content_type='application/json', **httpresponse_kwargs)

    def convert_context_to_json(self, context):
        return json.dumps(context)

atados/nonprofit/views.py
from django.core.exceptions import PermissionDenied
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.utils.decorators import classonlymethod
from atados.nonprofit.models import Nonprofit
from atados.nonprofit.forms import (NonprofitPictureForm,
                                       NonprofitDetailsForm)


class NonprofitMixin(object):
    nonprofit = None
    only_owner = True

    def get_context_data(self, **kwargs):
        context = super(NonprofitMixin, self).get_context_data(**kwargs)
        context.update({'nonprofit': self.get_nonprofit()})
        return context

    def dispatch(self, request, *args, **kwargs):
        self.nonprofit = get_object_or_404(Nonprofit,
                                              slug=kwargs.get('nonprofit'))
        if self.only_owner and self.nonprofit.user != request.user:
            raise PermissionDenied
        return super(NonprofitMixin, self).dispatch(request,
                                                       *args, **kwargs)

    def get_nonprofit(self):
        return self.nonprofit

class NonprofitBaseView(NonprofitMixin, TemplateView):
    pass

class NonprofitHomeView(TemplateView):
    template_name = 'atados/nonprofit/home.html'

class NonprofitDetailsView(NonprofitBaseView):
    only_owner = False
    template_name = 'atados/nonprofit/details.html'

class NonprofitPictureUpdateView(NonprofitMixin, UpdateView):
    model = Nonprofit
    form_class=NonprofitPictureForm
    template_name='atados/nonprofit/picture.html'
    get_object = NonprofitMixin.get_nonprofit

class NonprofitDetailsUpdateView(NonprofitMixin, UpdateView):
    model = Nonprofit
    form_class=NonprofitDetailsForm
    template_name='atados/nonprofit/edit-details.html'
    get_object = NonprofitMixin.get_nonprofit

atados/volunteer/views.py
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.utils.decorators import classonlymethod
from atados.volunteer.models import Volunteer
from atados.volunteer.forms import VolunteerPictureForm


class UserReferenceMixin(object):
    only_owner = True
    user = None

    def get_context_data(self, **kwargs):
        context = super(UserReferenceMixin, self).get_context_data(**kwargs)
        context.update({'user_reference': self.get_user_reference()})
        return context

    def dispatch(self, request, *args, **kwargs):
        if self.only_owner and request.user.username != kwargs.get('username'):
            raise Http404
        return super(UserReferenceMixin, self).dispatch(request,
                                                        *args, **kwargs)
 
    def get_user_reference(self):
        if self.user is None:
            self.user = get_object_or_404(User,
                                          username=self.kwargs.get('username'))
        return self.user

class VolunteerMixin(UserReferenceMixin):
    volunteer = None
    only_owner = True

    def get_context_data(self, **kwargs):
        context = super(VolunteerMixin, self).get_context_data(**kwargs)
        context.update({'volunteer': self.get_volunteer()})
        return context

    def dispatch(self, request, *args, **kwargs):
        self.kwargs = kwargs
        self.volunteer = get_object_or_404(Volunteer,
                                           user=self.get_user_reference())
        if self.only_owner and self.volunteer.user != request.user:
            raise PermissionDenied
        return super(VolunteerMixin, self).dispatch(request,
                                                    *args, **kwargs)

    def get_volunteer(self):
        return self.volunteer

class VolunteerBaseView(VolunteerMixin, TemplateView):
    pass

class VolunteerHomeView(TemplateView):
    template_name = 'atados/volunteer/home.html'

class VolunteerDetailsView(VolunteerBaseView):
    only_owner = False
    template_name = 'atados/volunteer/details.html'

class VolunteerPictureUpdateView(VolunteerMixin, UpdateView):
    model = Volunteer
    form_class=VolunteerPictureForm
    template_name='atados/volunteer/picture.html'
    get_object = VolunteerMixin.get_volunteer

atados/nonprofit/templates/atados/nonprofit/base.html
{% extends 'atados/atados/base.html' %}
{% load i18n %}

atados/nonprofit/templates/atados/nonprofit/details.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n thumbnail %}

{% block breadcrumb %}
<li class="active">{{ nonprofit.name }}</li>
{% endblock %}

{% block content %}
<div id="nonprofit-details">
  <div class="row">
    <div class="span12">
      <h1>{{ nonprofit.name }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="span3">
      <div class="profile-picture">
        {% thumbnail nonprofit.image "220x220" crop="center" as im %}
        <img class="img-rounded" alt="{{ nonprofit }}" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
        {% if nonprofit in nonprofit_list %}
        <a class="btn" href="{% url nonprofit:edit-nonprofit-picture nonprofit.slug %}"><i class="icon-edit"></i> {% trans "Edit profile picture" %}</a>
        {% endif %}
        {% empty %}
        <div class="img-rounded icon nonprofit large"></div>
        {% if nonprofit in nonprofit_list %}
        <a class="btn" href="{% url nonprofit:edit-nonprofit-picture nonprofit.slug %}"><i class="icon-edit"></i> {% trans "Add profile picture" %}</a>
        {% endif %}
        {% endthumbnail %}
      </div>
      <div class="row">
        <div class="span3">
          <h2 style="margin-top:12px">{% trans "Volunteers" %}</h2>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <img class="img-rounded" style="width:42px; float:left; margin:0 10px 10px 0" src="{{ STATIC_URL }}/img/dummy.jpg" />
          <div style=""><a href="#">Rogerio da Silva Yokomizo</a></div>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <img class="img-rounded" style="width:42px; float:left; margin:0 10px 10px 0" src="{{ STATIC_URL }}/img/dummy.jpg" />
          <div style=""><a href="#">Rogerio Yokomizo</a></div>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="well well-light">
        <div class="well-header">
          <h2>{% trans "Projects" %}</h2>
          {% if nonprofit in nonprofit_list %}
          <div>
            <a href="{% url project:new nonprofit.slug %}">{% trans "New project" %}</a>
          </div>
          {% endif %}
        </div>
        <ul class="projects">
          {% for project in nonprofit.project_set.all %}
          <li class="row-fluid">
            <div class="span2">
              {% thumbnail project.image "60x60" crop="center" as im %}
              <a href="{{ project.get_absolute_url }}"><img class="img-rounded" alt="{{ project }}" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" /></a>
              {% empty %}
              <a href="{{ project.get_absolute_url }}" class="img-rounded icon project small"></a>
              {% endthumbnail %}
            </div>
            <div class="span10">
              <a href="{{ project.get_absolute_url }}">{{ project.name }}</a>
              <p>{{ project.details }}</p>
            </div>
          </li>
          {% empty %}
          <li>{% trans "This nonprofit doesn't have any projects." %}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="span3">
      <div class="well">
        <div class="well-header">
          <h2>{% trans "Nonprofit" %}</h2>
          {% if nonprofit in nonprofit_list %}
          <div>
            <a href="{% url nonprofit:edit-nonprofit-details nonprofit.slug %}">{% trans "Edit" %}</a>
          </div>
          {% endif %}
        </div>
        <p>
        {% if nonprofit.details %}
          {{ nonprofit.details }}
        {% else %}
          {% trans "Nothing about this nonprofit" %}
        {% endif %}
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/edit-details.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block breadcrumb %}
<li><a href="{{ nonprofit.get_absolute_url }}">{{ nonprofit.name }}</a></li>
<li class="active">{% trans "Edit nonprofit details" %}</li>
{% endblock %}

{% block content %}
<form class="well" action="{% url nonprofit:edit-nonprofit-details nonprofit.slug %}" method="post">{% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
  </div>
</form>
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/home.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit thumbnail %}

{% block out_breadcrumb %}
{% endblock %}

{% block js %}
<script>$('.volunteer-link').tooltip({'placement': 'right'});</script>
{% endblock %}

{% block content %}

<div id="nonprofit-home">
  {% for nonprofit in nonprofit_list %}
  <div class="row">
    <div class="span1">
      <a href="{% url slug nonprofit.slug %}">
        {% thumbnail nonprofit.image "60x60" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-rounded" />
        {% empty %}
        <div class="img-rounded icon nonprofit small"></div>
        {% endthumbnail %}
      </a>
    </div>
    <div class="span11">
      <h1><a href="{% url slug nonprofit.slug %}">{{ nonprofit.name }}</a></h1>
    </div>
  </div>
  <div class="row">
    <div class="span8">
      ...
    </div>
    <div class="span4">
      <div class="row">
        <div class="span2">
          <h2>{% trans "Projects" %}</h2>
        </div>
        <div style="text-align:right" class="span2">
          <a class="btn btn-primary btn-small" href="{% url project:new nonprofit.slug %}">{% trans "New project" %}</a>
        </div>
      </div>
      <ul class="nav nav-tabs nav-stacked">
      {% for project in nonprofit.project_set.active %}
        <li><a href="{{ project.get_edit_url }}">{{ project.name }}</a></li>
      {% empty %}
        <li>{% trans "Your nonprofit does not have any project" %}</li>
      {% endfor %}
      </ul>
    </div><!-- /.span4 -->
  </div><!-- /.row -->
  {% endfor %}
</div>
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/picture.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block breadcrumb %}
<li><a href="{{ nonprofit.get_absolute_url }}">{{ nonprofit.name }}</a></li>
<li class="active">{% trans "Edit nonprofit picture" %}</li>
{% endblock %}

{% block content %}
<form class="well" action="{% url nonprofit:edit-nonprofit-picture nonprofit.slug %}" method="post" enctype="multipart/form-data">{% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">{% trans "Upload" %}</button>
  </div>
</form>
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/sign-up-activation-complete.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block content %}
TO DO
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/sign-up-activation.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block content %}
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/sign-up-complete.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block content %}
TO DO (re-send)
{% endblock %}

atados/nonprofit/templates/atados/nonprofit/sign-up.html
{% extends 'atados/nonprofit/base.html' %}
{% load i18n bootstrap_toolkit %}

{% block breadcrumb %}
<li class="active">{% trans "Post a project" %}</li>
{% endblock %}

{% block content %}
<div id="nonprofit-sign-up">
  <div class="page-header">
    <h1>{% trans "Sign up to find more volunteers" %}</h1>
  </div>

  <div class="row">
    <div class="span6 reasons">
      <div class="row">
        <div class="span3">
          <img class="img-rounded" src="{{ STATIC_URL }}/img/dummy.jpg" width="220" height="220" />
        </div>
        <div class="span3">
          <h2>{% trans "Management platform free." %}</h2>
          <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sagittis mattis tincidunt. Sed at mauris eu lacus egestas fringilla vitae.
          </p>
        </div>
      </div>

      <div class="row">
        <div class="span3">
          <img class="img-rounded" src="{{ STATIC_URL }}/img/dummy.jpg" width="220" height="220" />
        </div>
        <div class="span3">
          <h2>{% trans "Find volunteers with specific skills" %}</h2>
          <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nisi neque, pulvinar at viverra iaculis, gravida quis sem. Suspendisse iaculis.
          </p>
        </div>
      </div>

    </div>
    <div class="span6">
      <form class="well" method="post" action="{% url nonprofit:sign-up %}">{% csrf_token %}
        {{ form|as_bootstrap }}
        <div class="form-terms alert">
          {% url atados:home as terms_url %}
          {% url atados:home as privacy_url %}
          {% blocktrans %}
          By clicking Sign Up, you are indicating that you have read and agree to the <a tabindex="-1"href="{{ terms_url }}">Terms of Service</a> and <a tabindex="-1" href="{{ privacy_url }}">Privacy Policy</a>.
          {% endblocktrans %}
        </div>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">{% trans "Sign up" %}</button>
        </div>
      </form>
    </div>
  </div>

</div>
{% endblock %}